name: 'README Template KPS-Universe'
description: 'Github Action to render README Template'
author: 'DorianVelazquez'
branding:
  icon: 'upload-cloud'
  color: 'purple'
inputs:
  REPOSITORIES:
    description: 'Name of the projects'
    required: true
  TOKEN:
    description: 'Personal access token with Repo privileges'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
