name: 'README Template KPS-Universe'

description: 'Github Action to render README Template'
author: 'DorianVelazquez'
branding:
  icon: 'upload-cloud'
  color: 'purple'

runs:
  using: 'docker'
  image: 'Dockerfile'
